services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=AuctionDb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgresviewer
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@carsties.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
  
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    ports:
      - 7000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


  auctionSvc:
    container_name: Carsties.AuctionService
    image: trycatchlearn/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLs=http://+80
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - AppConfigurations__ApplicationIdentifier=Carsties.AuctionService
      - AppConfigurations__ApplicationEnvironment=Development
      - Elasticsearch__Uri=http://elasticsearch:9200
      - IdentityGroupAccess__Authority=http://identity-svc:5000
      - IdentityGroupAccess__Audience=http://identity-svc:5000/resources
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - ConnectionStrings__CarstiesConnection=Server=postgres:5432;Database=AuctionDb;User Id=admin;Password=admin1234;
    ports:
      - 4001:80
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:    
  pgadmin_data:    
  mongodata:
  portainer_data: