import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import Navbar from "./components/nav/navbar";
import "./globals.css";

const tittlium = Titillium_Web({
  weight: ["200", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Carsties Auctions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={tittlium.className}>
        <Navbar />
        <main className="container mx-auto px-5 pt-10 pb-10">{children}</main>
      </body>
    </html>
  );
}
